- name: Remove existing directory
  ansible.builtin.file:
    path: "{{ app_dir }}"
    state: absent

- name: Clone a git repository
  ansible.builtin.git:
    repo: 'https://github.com/oleg-oleynikov/testTaskRocketDev'
    dest: "{{ app_dir }}"
    version: main
    update: true
    force: true




