- name: Configure all servers
  hosts: webservers
  become: true
  
  tasks:
    - name: Git setup
      include_tasks: playbooks/git.yaml
      when: install_git | default(true)
    
    - name: Python pip setup
      include_tasks: playbooks/python.yaml

    - name: Docker setup
      include_tasks: playbooks/docker.yaml