- name: Configure servers
  hosts: webservers
  become: true
  
  tasks:
    - name: Git check
      include_tasks: playbooks/git.yaml
      when: install_git | default(true)
    
    - name: Python pip check exists
      include_tasks: playbooks/python.yaml

    - name: Docker check exists
      include_tasks: playbooks/docker.yaml
    
    - name: Clone git repository
      include_tasks: playbooks/repo.yaml
    
    - name: Download and configure fail2ban
      include_tasks: playbooks/fail2ban.yamlS